version: '2'

services:
  lot_sizing:
    build: .
    image: postgres_eer_model:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: CAPACITATED_LOT_SIZING

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080